fos_rest:
  param_fetcher_listener: force
  body_converter:
    enabled: true
  view:
    view_response_listener:  true
  format_listener:
    rules:
      - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
